fos_user:
  db_driver: orm
  firewall_name: main
  user_class: App\Entity\User
  from_email:
    address: "%env(mailer_email)%"
    sender_name: "%env(mailer_name)%"
  service:
    mailer: fos_user.mailer.twig_swift